DanielNoord/pydocstringformatter

pydocstringformatter/formatting.py
pydocstringformatter/formatting/__init__.py
pydocstringformatter/formatting/formatter.py
pydocstringformatter/run.py
pyproject.toml

This is a proposition so it's easier to add Formatter later on and remove some duplicated calls. (Based on #8)

Refactor of the formatter to scale better later on

---

pydocstringformatter/formatting/base.py
pydocstringformatter/formatting/formatter.py

Create a file for the base classes for Formatters

---

.github/CONTRIBUTING.md
pydocstringformatter/formatting/__init__.py
pydocstringformatter/formatting/base.py
pydocstringformatter/formatting/formatter.py
tests/test_formatter.py

Splitting the consensual part of #15

Add a name and an optional attribute to Formatters

---

pydocstringformatter/run.py
pydocstringformatter/utils/__init__.py
pydocstringformatter/utils/file_diference.py
tests/data/format/no_changes/multi_line_variables.py.out
tests/test_config.py
tests/test_formatting.py
tests/test_run.py

Closes #2 
It's a bit annoying to have to check for `diffs` in the non-formatting unittests, but I think we can manage. If the `endswith` becomes too long we can always do `starswith("---")` although the `endswith` also provides a good sanity check that nothing is wrong with the actual diff.

Print out ``diff`` instead of complete file for formatting changes

---

.github/CONTRIBUTING.md
pydocstringformatter/run.py
pydocstringformatter/utils/__init__.py
pydocstringformatter/utils/argument_parsing.py
tests/test_run.py

Work in progress, this still need more robust tests. This would permit to automatically generate the arguments and to activate or deactivate every parser while still having a default.

Make every formatter optional

---

README.md
pydocstringformatter/configuration/arguments_manager.py
pydocstringformatter/configuration/toml_parsing.py
pydocstringformatter/configuration/validators.py
pydocstringformatter/run.py
pydocstringformatter/utils/find_python_file.py
tests/data/config/exclude_match/pyproject.toml
tests/data/config/exclude_match/test_package/incorrect_docstring.py
tests/data/config/exclude_match_csv/pyproject.toml
tests/data/config/exclude_match_csv/test_package/incorrect_docstring.py
tests/data/config/exclude_match_csv_list/pyproject.toml
tests/data/config/exclude_match_csv_list/test_package/incorrect_docstring.py
tests/data/config/exclude_match_inner/pyproject.toml
tests/data/config/exclude_match_inner/test_package/inner_dir/incorrect_docstring.py
tests/data/config/exclude_non_match/pyproject.toml
tests/data/config/exclude_non_match/test_package/incorrect_docstring.py
tests/test_config.py
tests/test_utils.py

Closes #1 
`glob` is apparently pretty bad for ignoring stuff and is only used to capture things. (include vs. exclude).
However, for now I think this will be fine. I'm not sure about the tests and whether this catches everything, but at least we can get feedback if this works now!

Add an ``exclude`` option to exclude files based on ``glob`` patterns

---

pydocstringformatter/configuration/formatter_options.py

Follow up to #32, which uses the new properties throughout the codebase.

Use ``(de)activate_option`` properties outside of tests

---

README.md
pydocstringformatter/formatting/formatter.py
tests/data/format/final_period/function_title_docstrings.py
tests/data/format/final_period/function_title_docstrings.py.out

First step towards #36.
This already works with the current code, but now when we change anything in `FinalPeriodFormatter` we make sure that this keeps working.
Second step would be to recognise Sphinx-style titles in ``BeginningQuotesFormatter``.

Special case Sphinx-style titles for ``FinalPeriodFormatter``

---

.pre-commit-config.yaml
pydocstringformatter/__init__.py
pydocstringformatter/formatting/base.py
pydocstringformatter/formatting/formatter.py
tests/data/format/capitalization_first_letter/single_quote_docstring.py
tests/data/format/capitalization_first_letter/single_quote_docstring.py.out
tests/data/format/final_period/single_quote_docstring.py
tests/data/format/final_period/single_quote_docstring.py.out
tests/data/format/whitespace_stripper/single_quote_docstring.py
tests/data/format/whitespace_stripper/single_quote_docstring.py.out

Fixes a part of #45.
I'd like to add the quotes formatter as well to `0.4.0` so we can also fix the underlying issue when running the formatter over `pylint` 😄

Handle docstrings in single quoted strings correctly

---

pydocstringformatter/formatting/formatter.py
tests/data/format/final_period/exotic_line_ending.py
tests/data/format/final_period/exotic_line_ending.py.out

This permit to stay sane for this:
```diff
-        """Check the name of first argument, expect:
+        """Check the name of first argument, expect:.
* 'self' for a regular method
* 'cls' for a class method or a metaclass regular method (actually
```

Add ':' and ';' to allowed punctuation

---

.gitignore
.readthedocs.yaml
docs/Makefile
docs/_static/custom.css
docs/conf.py
docs/index.rst
docs/make.bat
docs/requirements-doc.txt
requirements-test.txt

Create ``docs`` and use Readthedocs for hosting

---

pydocstringformatter/configuration/arguments_manager.py
pydocstringformatter/configuration/formatter_options.py
tests/test_run.py

With this change the help message is now:
```console
usage: pydocstringformatter [-h] [-w] [--quiet] [-v] [--exclude EXCLUDE] [--split-summary-body] [--no-split-summary-body] [--strip-whitespaces]
[--no-strip-whitespaces] [--beginning-quotes] [--no-beginning-quotes] [--closing-quotes] [--no-closing-quotes]
[--capitalize-first-letter] [--no-capitalize-first-letter] [--final-period] [--no-final-period] [--quotes-type]
[--no-quotes-type]
[files ...]
positional arguments:
files                 The directory or files to format.
options:
-h, --help            show this help message and exit
-w, --write           Write the changes to file instead of printing the diffs to stdout.
--quiet               Do not print any logging or status messages to stdout.
-v, --version         Show version number …
```

Separate optional and non-optional formatters in help message

---

.github/workflows/checks.yaml
.pre-commit-config.yaml
README.md
docs/_ext/link_fixer.py
docs/_ext/usage_page.py
docs/conf.py
docs/index.rst
docs/requirements-doc.txt
docs/usage.rst
requirements-test.txt

Let's see how this works.
Edit: Left to do:
- Make sure the documentation builds within the `pre-commit`. Current challenge is forcing `pre-commit` to install `-e .` before running the `docs` makefile. That is necessary to build the most recent version of the documentation.

Add a usage page to the documentation

---

docs/usage.rst
pydocstringformatter/configuration/arguments_manager.py
pydocstringformatter/formatting/formatter.py
tests/data/format/summary_splitter/class_docstring.py.out
tests/data/format/summary_splitter/dots.args
tests/data/format/summary_splitter/dots.py
tests/data/format/summary_splitter/dots.py.out
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_1.args
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_1.py
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_1.py.out
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_2.args
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_2.py
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_2.py.out
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_3.args
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_3.py
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_3.py.out
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_default.args
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_default.py
tests/data/format/summary_splitter/max_summary_lines/max_lines_is_default.py.out
tests/data/format/summary_splitter/max_summary_lines/max_lines_with_dot.args
tests/data/format/summary_splitter/max_summary_lines/max_lines_with_dot.py
tests/data/format/summary_splitter/max_summary_lines/max_lines_with_dot.py.out
tests/test_formatting.py

I have tested this (partially) on `pylint` and with `max-summary-lines=2` I think we can turn this on for `pylint`.
I'd like to do that first and then release `0.6.0` with the wrapping of lines. That should make the diff somewhat more manageable.

Improve ``SplitSummaryAndDocstringFormatter``

---

.github/workflows/tests.yaml
pydocstringformatter/__init__.py
pydocstringformatter/formatting/base.py
pydocstringformatter/formatting/formatter.py
tests/data/format/summary_splitter/ending_quotes.args
tests/data/format/summary_splitter/ending_quotes.py
tests/data/format/summary_splitter/ending_quotes.py.out

Closes #67 and fixes a bug encountered in ``pylint``.

Fix the ``SummaryFormatter``

---

.pre-commit-config.yaml
pydocstringformatter/utils/file_diference.py
tests/test_config.py
tests/test_run.py

This is necessary for the primer and doesn't matter too much in normal use.

Add a newline to the end of the diff output

---

docs/usage.rst
pydocstringformatter/configuration/arguments_manager.py
pydocstringformatter/run.py
pydocstringformatter/utils/__init__.py
pydocstringformatter/utils/output.py
tests/test_config.py
tests/test_run.py
tests/test_utils.py

Closes #4.
Also moved some stuff around and updated the output a little.
I kept the proposed exit codes as it just makes everything future proof.
For future reference:
0 - Nothing happened, all files are fine.
1 - Internal error
2 - Config parsing error
4, 8, 16 - Empty for future use
32 - A file was changed or could be changed
64, 128, 256 - Empty for future use

Add ``--exit-code`` option and add number of files to output

---

.github/workflows/primer.yaml
.gitignore
docs/development.rst
pydocstringformatter/testutils/primer/const.py
pydocstringformatter/testutils/primer/packages.py
pydocstringformatter/testutils/primer/primer.py
pyproject.toml
requirements-test.txt

Add primer tests

---

pydocstringformatter/formatting/base.py
tests/data/format/summary_splitter/function_docstrings.py
tests/data/format/summary_splitter/function_docstrings.py.out

Closes #86.
Don't really like this `prefix` stuff. But it works for now.

Fix handling of summaries on a separate line

---

docs/usage.rst
pydocstringformatter/formatting/__init__.py
pydocstringformatter/formatting/base.py
pydocstringformatter/formatting/formatter.py
tests/data/format/linewrap_summary/function_docstrings.args
tests/data/format/linewrap_summary/function_docstrings.py
tests/data/format/linewrap_summary/function_docstrings.py.out

Partially handles #7, it's not even close right now 😄 The line wrapping fail because there are space before and after the leading string.

Add line wrapping to summaries of docstrings

---

pydocstringformatter/formatting/formatter.py
tests/data/format/linewrap_summary/function_docstrings.py
tests/data/format/linewrap_summary/function_docstrings.py.out

Fix the bug found in https://github.com/PyCQA/pylint/pull/6469#issuecomment-1112218219

Fix a bug with wrapping of single line summaries

---

pydocstringformatter/formatting/formatter.py
tests/data/format/whitespace_stripper/function_docstrings.py
tests/data/format/whitespace_stripper/function_docstrings.py.out

Improve removal of unnecessary or double white lines

---

README.md
docs/usage.rst
pydocstringformatter/configuration/arguments_manager.py
pydocstringformatter/formatting/base.py
pydocstringformatter/formatting/formatter.py
requirements-test.txt
tests/data/format/linewrap_summary/max_line_length_50.args
tests/data/format/linewrap_summary/max_line_length_50.py
tests/data/format/linewrap_summary/max_line_length_50.py.out

Small update to have max-line-length as a argument.
Sorry, but didn't have time to make tests pass. Some magic happens below :stuck_out_tongue: 
Closes https://github.com/DanielNoord/pydocstringformatter/issues/90

Max line length

---

.gitattributes
.pre-commit-config.yaml
pydocstringformatter/run.py
pyproject.toml
tests/data/format/newlines/dos.py
tests/data/format/newlines/dos.py.out
tests/data/format/newlines/mac.py
tests/data/format/newlines/mac.py.out
tests/data/format/newlines/mixed.err
tests/data/format/newlines/mixed.py
tests/data/format/newlines/mixed.py.out
tests/data/format/newlines/none.args
tests/data/format/newlines/none.py
tests/data/format/newlines/none.py-0d0a.out
tests/data/format/newlines/none.py.out
tests/data/format/newlines/unix.py
tests/data/format/newlines/unix.py.out
tests/test_formatting.py

Here's my proposed solution. It should work in all cases, as it will default to the system default, if the file has different line endings (`file.newlines` returns a tuple).
I manually tested it with Unix, Dos, and Mac formatted files, and they all retained their line endings.

fix: write file using existing newlines (fixes #115)

---

docs/usage.rst
pydocstringformatter/_configuration/arguments_manager.py
tests/test_config.py

Currently only supports ``--style pep257``

Add the ``--style`` option

---

docs/usage.rst
pydocstringformatter/_configuration/arguments_manager.py
pydocstringformatter/_formatting/__init__.py
pydocstringformatter/_formatting/base.py
pydocstringformatter/_formatting/formatters_numpydoc.py
tests/data/format/numpydoc/numpydoc_header_line.args
tests/data/format/numpydoc/numpydoc_header_line.py
tests/data/format/numpydoc/numpydoc_header_line.py.out
tests/data/format/numpydoc/numpydoc_parameter_spacing.args
tests/data/format/numpydoc/numpydoc_parameter_spacing.py
tests/data/format/numpydoc/numpydoc_parameter_spacing.py.out
tests/data/format/numpydoc/numpydoc_section_ordering.args
tests/data/format/numpydoc/numpydoc_section_ordering.py
tests/data/format/numpydoc/numpydoc_section_ordering.py.out
tests/data/format/numpydoc/numpydoc_section_spacing.args
tests/data/format/numpydoc/numpydoc_section_spacing.py
tests/data/format/numpydoc/numpydoc_section_spacing.py.out
tests/data/format/numpydoc/numpydoc_style.args
tests/data/format/numpydoc/numpydoc_style.py
tests/data/format/numpydoc/numpydoc_style.py.out
tests/test_config.py

Related to #125; I got the bits I could think how to automate for the docstring style I actually use ([numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard))
Should probably extend the tests for more types of docstrings and more sections within each docstring.
Ideally the section test would have docstrings on
and would test the ordering of some subset of these sections:
Formatters for:

ENH: Add formatters for numpydoc section ordering and name/type spacing

---

pydocstringformatter/__init__.py
pydocstringformatter/_configuration/toml_parsing.py

Don't know how I didn't notice this sooner...
Releasing `0.7.1` immediately after.

Fix ``tomli`` vs ``tomllib`` import

---

pydocstringformatter/__init__.py
pydocstringformatter/_formatting/formatters_default.py
pydocstringformatter/_formatting/formatters_pep257.py
tests/data/format/summary_splitter/regression_151.py
tests/data/format/summary_splitter/regression_151.py.out

Fix crash with almost empty docstrings

---

docs/usage.rst
pydocstringformatter/_formatting/__init__.py
tests/data/format/numpydoc/numpydoc_regression.args
tests/data/format/numpydoc/numpydoc_regression.py
tests/data/format/numpydoc/numpydoc_regression.py.out

As seen in https://github.com/DanielNoord/pydocstringformatter/pull/156/

Fix adding whitespaces in ``numpydoc`` style to single line docstrings

---

.pre-commit-config.yaml
pydocstringformatter/_configuration/toml_parsing.py
tests/data/config/valid_toml_numpydoc/pyproject.toml
tests/data/config/valid_toml_numpydoc/test_package/numpydoc_style.py
tests/data/config/valid_toml_numpydoc_pep257/pyproject.toml
tests/data/config/valid_toml_numpydoc_pep257/test_package/numpydoc_style.py
tests/data/config/valid_toml_pep257/pyproject.toml
tests/data/config/valid_toml_pep257/test_package/numpydoc_style.py
tests/test_config.py

Closes https://github.com/DanielNoord/pydocstringformatter/issues/155

fixed toml parser ignoring style

---

pydocstringformatter/_formatting/formatters_default.py
tests/data/format/summary_splitter/empty_summary.args
tests/data/format/summary_splitter/empty_summary.py
tests/data/format/summary_splitter/empty_summary.py.out

Discussed in the second section of:
Closes partially and therefore refs https://github.com/DanielNoord/pydocstringformatter/issues/160

fixed bug where empty summaries fail with index error

---

README.md
pydocstringformatter/_configuration/toml_parsing.py
tests/data/config/non_valid_toml_boolopt/pyproject.toml
tests/data/config/non_valid_toml_boolopt/test_package/numpydoc_style.py
tests/data/config/non_valid_toml_boolopt_two/pyproject.toml
tests/data/config/non_valid_toml_boolopt_two/test_package/numpydoc_style.py
tests/data/config/valid_toml_boolopt/pyproject.toml
tests/data/config/valid_toml_boolopt/test_package/numpydoc_style.py
tests/test_config.py

Improved the toml parsing so it supports `BooleanOptionalAction` arguments in it.
(also added tests for it ...)
```toml
[tool.pydocstringformatter]
write = false
style = ["numpydoc"]
strip-whitespaces = true  # <<<<<- previously unsupported
split-summary-body = false # <<<<<- previously unsupported
no-numpydoc-section-hyphen-length = true # <<<<<- previously unsupported
```
.... where should I document this?

added boolean optional argument support

---

pydocstringformatter/run.py

discussed here: https://github.com/DanielNoord/pydocstringformatter/pull/173/files/8732c21c8716963e33db8935c2e7db6dbd1e29e3#r973577060

renamed 'changed_tokens' ro 'formatted_tokens'

---

pydocstringformatter/_testutils/__init__.py
pydocstringformatter/_testutils/example_formatters.py
pydocstringformatter/_utils/__init__.py
pydocstringformatter/_utils/file_diference.py
tests/test_utils.py

Based on work in https://github.com/DanielNoord/pydocstringformatter/pull/173 by @jspaezp

Add example formatters and a ``compare_formatter`` utility

---

pydocstringformatter/_formatting/formatters_numpydoc.py
tests/data/format/numpydoc/numpydoc_closing_quotes.args
tests/data/format/numpydoc/numpydoc_closing_quotes.py
tests/data/format/numpydoc/numpydoc_closing_quotes.py.out

Closes https://github.com/DanielNoord/pydocstringformatter/issues/177

Don't add a new line in one-line Numpy docstrings

---

pydocstringformatter/_testutils/__init__.py
pydocstringformatter/_testutils/example_formatters.py
pydocstringformatter/_utils/__init__.py
pydocstringformatter/_utils/exceptions.py
pydocstringformatter/_utils/issue_template.py
pydocstringformatter/run.py
tests/data/format/linewrap_summary/function_docstrings.py.out
tests/test_conflicting_formatters.py

Discussed here:
https://github.com/DanielNoord/pydocstringformatter/issues/169
Things to iron out:
https://github.com/DanielNoord/pydocstringformatter/issues/169#issuecomment-1249090803
> I haven't looked at your branch as I am on mobile, but I'm highly in favour of this change. I'll gladly help review a PR but sadly won't have time to work on this myself this week.
> 
> Some pointers to consider:
> 
>     * I think the maximum run count should be 2.
> 
>     * After the second run, a third run should occur. If we still create changes (note that these should ignore the --write flag but should only check if there are any potential change) we need to emit an error. `black` has a very elegant system where after there is an inconsistency aftwr 2/3 runs a pre-regenerated bug report is send to …

Feature: two-pass formatting of the tokens

---

pydocstringformatter/_formatting/base.py
tests/data/format/quotes_type/mix_with_double_at_start.py
tests/data/format/quotes_type/mix_with_double_at_start.py.out
tests/data/format/quotes_type/mix_with_single_at_start.py
tests/data/format/quotes_type/mix_with_single_at_start.py.out

Closes https://github.com/DanielNoord/pydocstringformatter/issues/489
I guess that regex was always doomed to fail.
This should fix it. There are some weird changes that I don't particularly like.
For example, capitalization in `"""'A.m.' or 'p.m.'."""` is not desired I think...
Also `""""""a.m.""" or "p.m."."""` is invalid syntax.
However, we have always said that we can't format everything perfectly and "crap in is crap out". Since this at least fixes the bug I think it is still an improvement.

Fix regex to deal with mixing of quotes at start of string
